### ISSUE TITLE
nginx-gridfs hangs on files larger than 128kb

### ISSUE THREAD

**Issue by marcboeker** [mdirolf/nginx-gridfs#1] opened 2009-08-10 17:00 UTC
hi mike,

as described on IRC, heres the wget output. the download progress locks after approx. 128kb. and waits until a timout occurs. tested on ubuntu 9.04,  2.6.26-2-openvz-amd64.

HTTP request sent, awaiting response... 200 OK
Length: 2885436 (2.8M) [text/plain]
Saving to: `2931761775_4e08850357_o.jpg'

 4% [===>                                                                                                   ] 130,920     --.-K/s  eta 2m 40s

cheers marc

**Comment by mdirolf** [comment] 2009-12-18 17:51
Haven't been able to reproduce this yet, will try to take a look this weekend

**Comment by jszmajda** [comment] 2009-12-18 19:26
This happens to me too. Nginx's error.log has stuff like this:

2009/12/18 12:20:09 [alert] 4274#0: *13 writev() failed (14: Bad address), client: 127.0.0.1, server: localhost, request: "GET /gridfs/stock.zip HTTP/1.0", host: "127.0.0.1:8082"
2009/12/18 12:20:11 [alert] 4274#0: *14 writev() failed (14: Bad address), client: 127.0.0.1, server: localhost, request: "GET /gridfs/stock.zip HTTP/1.0", host: "127.0.0.1:8082"

and wget tries to reconnect infinitely

**Comment by mdirolf** [comment] 2009-12-18 19:33
Okay must be something I'm breaking. Planning on removing the C++ driver dependency in favor of the C driver (or just custom socket code depending on how aggressive I'm feeling ;), so maybe this will get cleaned up then.

Thanks for the comments and patches, btw - inspiring me to work on this some more.

**Comment by jszmajda** [comment] 2009-12-18 22:28
I'd love to be able to use this in a production environment, I'll try and help out more if I can, but I think my C skills might be a little too rusty.

**Comment by sho** [comment] 2009-12-19 15:44
For what it's worth - I have actually never seen this issue. I am routinely serving files in excess of 128KB on OSX and RHEL5. It seems there is some funky stuff going on between different versions of linux?

Just ran a small stress test getting a 1.8M image 50k times from nginx-gridfs; zero errors. Are there any conditions which seem to exacerbate the problem?

**Comment by jszmajda** [comment] 2009-12-22 12:51
sho, are you using the 32bit mongo or 64bit mongo? Maybe that's the difference? I'm on mongodb-linux-i686-1.2.0

**Comment by sho** [comment] 2009-12-22 15:20
oh that is very possible. I am using 64bit exclusively.

Hm but it looks like the OP on this ticket was using 64? No idea. But anyway yeah 64bit.

**Comment by mdirolf** [comment] 2009-12-22 15:22
hmm i think it's unlikely that server version makes a difference, but possible. some big changes (improvements) coming for this project soon, hence i've been a little bit slow responding on these bug reports. am hoping to squash some of them with the new code.

**Comment by sho** [comment] 2009-12-22 15:28
mdirolf that sounds awesome, can't wait! 

yeah, no point laboriously debugging soon-to-be-obsolete code ....

**Comment by mdirolf** [comment] 2010-06-18 17:27
can you try this again? chris has converted everything to use the mongo-c-driver and re-worked a bunch of stuff

**Comment by sdizier** [comment] 2011-03-16 16:54
Has this problem been fixed?  Can anyone confirm?

**Comment by doxavore** [comment] 2011-10-31 22:49
I have been using the driver in production with no issue since the conversion to the mongo-c-driver. Our users regularly upload 20-100MB files through it.

**Comment by mdirolf** [comment] 2011-10-31 23:12
Thanks for the update - I'm marking this as closed (feel free to reopen if anybody experiences further issues).

**Closed as completed by mdirolf** 2011-10-31 23:12 UTC
